# Generated by Django 6.0.6 on 2026-06-28 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="criador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receitas_criadas",
                to="receitas.utilizador",
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="ingredientes",
            field=models.ManyToManyField(
                related_name="receitas", to="receitas.ingrediente"
            ),
        ),
    ]
